### ISSUE TITLE
Repeated verses issue

### ISSUE THREAD

**Issue by Imperial7** [quran/quran.com-frontend-v2#342] opened 2021-02-08 16:01 UTC
there is a problem occurs whenever you press the different play button

the bug is basically two or more verses audios can be played at the same time

**To Re-produce the bug:**

1- Open any Surah, for example: https://quran.com/97/1

2- Play the audio using the main play button at the bottom, and hit pause before the verse audio finishes

3- on the top menu, select the another verse (Verse 2 in this example) from the dropdown menu

4- now in the second verse page hit play from the left side menu (not the main play button) and then hit pause before the audio finishes playing

5- Now hit the main play button (the bottom one) and you should be able to hear the both verses audios playing together at the same time

**Comment by benomaire** [comment] 2021-02-09 10:45
6. and if you hit the main play button again, things are more strange

BTW, why would you pause and shift to the next ayah ?
You can avoid this bug by showing the whole Surah at once: https://quran.com/97 

I think this will be fixed in the coming update. Checkout https://beta.quran.com/97/1
جزاكم الله خيرا

**Comment by SinadShan** [comment] 2021-02-26 04:27
I've experienced a similar bug. While skipping ahead by multiple verses, multiple verses are played at the same time causing overlapping of those audios. Pausing playback pauses only one of the verses that is being played.

**Comment by hoopoe1427** [comment] 2021-04-08 14:30
Yes that is true but the issue is intermittent it happens sometimes, I would suggest just going back or ahead more slowly

**Comment by naveed-ahmad** [comment] 2021-04-21 19:00
Fixed.

**Closed by naveed-ahmad** 2021-04-21 19:00 UTC
