### ISSUE TITLE
Donation and Feedback

### ISSUE THREAD

**Issue by tbasough** [quran/quran.com-frontend-v2#406] opened 2021-05-11 21:46 UTC
Donation button ain't working.
Feedbacks ain't submitting.

Check on them, or do you restrict some kinds of users?

**Comment by tashrifbillah** [comment] 2021-05-15 02:41
Same issue here. I wanted to donate some by the end of Ramadan since I became a fan of quaran.com. But I was hindered by the following upon clicking the `Donate` button:

![image](https://user-images.githubusercontent.com/35086881/118345878-8e316d80-b505-11eb-8e86-2da1e49958a7.png)

**Comment by tashrifbillah** [comment] 2021-05-15 02:43
By the way, @naveed-ahmad , did you already solve this issue by [this](https://github.com/quran/quran.com-frontend-v2/commit/df65faea4f57093d282f4aa046a1d6bec044809b) commit? However, the issue is still present in the donations tab:

https://quran.com/donations

**Comment by naveed-ahmad** [comment] 2021-05-16 00:48
Salam.Ramadan campaign is ended, so disabled the donation option on quran.com. You can still donate using quranfund.com

And we're going to start working on nextjs version. Contact form will be fixed shortly.

**Closed by naveed-ahmad** 2021-05-16 00:48 UTC
